ekf_filter_node:
  ros__parameters:
    use_sim_time: false           # Set to true only if using rosbag or simulator
    frequency: 30.0
    two_d_mode: true              # Since you're on a ground UGV
    publish_tf: true
    publish_acceleration: false
    print_diagnostics: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /odom
    odom0_config: [true,  true,  false,   # x, y, z
                   false, false, true,   # roll, pitch, yaw
                   true,  true,  false,  # vx, vy, vz
                   false, false, true,   # vroll, vpitch, vyaw
                   false, false, false]  # ax, ay, az
    odom0_differential: false

    imu0: /vectornav/imu
    imu0_config: [false, false, false,   # x, y, z
                  true,  true,  true,    # roll, pitch, yaw
                  false, false, false,   # vx, vy, vz
                  true,  true,  true,    # vroll, vpitch, vyaw
                  false, false, false]   # ax, ay, az
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true

