slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /ouster/scan
    use_map_saver: true
    mode: mapping
    localization_mode: false
    map_start_pose: [0.0, 0.0, 0.0]

    debug_logging: true
    throttle_scans: 1
    transform_publish_period: 0.02
    map_update_interval: 2.0
    resolution: 0.03                        # Increased resolution for finer map
    max_laser_range: 20.0                  # Ensure box within range
    minimum_time_interval: 0.1
    transform_timeout: 0.2
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.2           # Reduced to register short movements
    minimum_travel_heading: 0.2            # Reduced to register small rotations
    scan_buffer_size: 50                   # Larger buffer to preserve obstacles
    scan_buffer_maximum_scan_distance: 20.0
    link_match_minimum_response_fine: 0.2
    link_scan_maximum_distance: 1.0
    loop_search_maximum_distance: 10.0
    do_loop_closing: false                 # Temporarily disable for accurate box mapping
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.5
    loop_match_minimum_response_fine: 0.55

    # Correlation Parameters - Scan Matching
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Correlation Parameters - Loop Closure
    loop_search_space_dimension: 12.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan Matcher Parameters
    distance_variance_penalty: 0.7
    angle_variance_penalty: 1.2
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.05
    minimum_angle_penalty: 1.2
    minimum_distance_penalty: 0.7
    use_response_expansion: true

