amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "differential"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: /ouster/scan

amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odometry/filtered
    bt_loop_duration: 10
    default_server_timeout: 20
    enable_groot_monitoring: True
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_controller_selector_bt_node
    - nav2_goal_checker_selector_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.3
      movement_time_allowance: 20.0

    # Goal checker parameters
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.5      # <- Relaxed
      yaw_goal_tolerance: 3.14    # <- Allows stopping without rotating

    # DWB parameters - updated for improved obstacle avoidance & speed
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True

      # Velocity tuning
      min_vel_x: 0.05
      min_vel_y: 0.0
      max_vel_x: 10.0
      max_vel_y: 0.0
      max_vel_theta: 1.2
      min_speed_xy: 0.05
      max_speed_xy: 1.5
      min_speed_theta: 0.1

      acc_lim_x: 12.0
      acc_lim_y: 0.0
      acc_lim_theta: 3.5
      decel_lim_x: -3.5
      decel_lim_y: 0.0
      decel_lim_theta: -3.5

      # Sampling resolution
      vx_samples: 30
      vy_samples: 5
      vtheta_samples: 40

      # Trajectory simulation
      sim_time: 2.0
      linear_granularity: 0.03
      angular_granularity: 0.017
      transform_tolerance: 0.3

      # Goal tolerance and evaluation
      xy_goal_tolerance: 0.5               # <- Consistent with goal checker
      trans_stopped_velocity: 0.1
      short_circuit_trajectory_evaluation: True
      stateful: True

      # Critics - RotateToGoal removed
      critics: ["Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]

      BaseObstacle.scale: 0.6
      PathAlign.scale: 20.0
      PathAlign.forward_point_distance: 0.3
      GoalAlign.scale: 15.0
      GoalAlign.forward_point_distance: 0.2
      PathDist.scale: 15.0
      GoalDist.scale: 15.0



      
controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      # Enhanced footprint configuration with buffer zone
      footprint: "[[-0.29, -0.306], [0.29, -0.306], [0.29, 0.306], [-0.29, 0.306]]"
      footprint_padding: 0.05   # Additional safety buffer around footprint
      plugins: ["stvl_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.0  # Slightly reduced for smoother navigation
        inflation_radius: 0.5    # Increased for better clearance
      stvl_layer:
          plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
          enabled: true
          voxel_decay: 5.0
          decay_model: 0
          voxel_size: 0.05
          track_unknown_space: true
          unknown_threshold: 15
          mark_threshold: 0
          update_footprint_enabled: true
          combination_method: 1
          origin_z: 0.0
          publish_voxel_map: true
          transform_tolerance: 0.2
          mapping_mode: false
          map_save_duration: 60.0
          # Enhanced surface flattening parameters
          flatten_surface: true
          flatten_surface_threshold: 0.15  # Height difference threshold for flattening
          observation_sources: rgbd1_mark rgbd1_clear
          rgbd1_mark:
            data_type: PointCloud2
            topic: /ouster/points
            marking: true
            clearing: false
            obstacle_range: 5.0
            min_obstacle_height: 0.0     # Slightly raised to ignore small surface variations
            max_obstacle_height: 10.0
            expected_update_rate: 0.0
            observation_persistence: 0.0
            inf_is_valid: false
            filter: "voxel"
            voxel_min_points: 5          # Increased for noise reduction
            clear_after_reading: true
          rgbd1_clear:
            enabled: true
            data_type: PointCloud2
            topic: /ouster/points
            marking: false
            clearing: true
            max_z: 8.0
            min_z: 0.0                   # Adjusted for better ground plane detection
            vertical_fov_angle: 0.6
            vertical_fov_padding: 0.05
            horizontal_fov_angle: 6.29
            decay_acceleration: 5.0
            model_type: 1
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      # Enhanced footprint configuration with buffer zone
      footprint: "[[-0.29, -0.306], [0.29, -0.306], [0.29, 0.306], [-0.29, 0.306]]"
      footprint_padding: 0.05   # Additional safety buffer around footprint
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "stvl_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan base_scan
        scan:
          topic: /ouster/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
        base_scan:
          topic: /ouster/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      stvl_layer:
          plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
          enabled: true
          voxel_decay: 20.0
          decay_model: -1
          voxel_size: 0.05
          track_unknown_space: true
          unknown_threshold: 15
          mark_threshold: 0
          update_footprint_enabled: true
          combination_method: 1
          origin_z: 0.0
          publish_voxel_map: true
          transform_tolerance: 0.2
          mapping_mode: false
          map_save_duration: 60.0
          # Enhanced surface flattening parameters
          flatten_surface: true
          flatten_surface_threshold: 0.15  # Height difference threshold for flattening
          observation_sources: rgbd1_mark rgbd1_clear
          rgbd1_mark:
            data_type: PointCloud2
            topic: /ouster/points
            marking: true
            clearing: false
            obstacle_range: 3.0
            min_obstacle_height: 0.0     # Slightly raised to ignore small surface variations
            max_obstacle_height: 10.0
            expected_update_rate: 0.0
            observation_persistence: 0.0
            inf_is_valid: false
            filter: "voxel"
            voxel_min_points: 2          # Increased for noise reduction
            clear_after_reading: true
          rgbd1_clear:
            enabled: true
            data_type: PointCloud2
            topic: /ouster/points
            marking: false
            clearing: true
            max_z: 8.0
            min_z: 0.0                   # Adjusted for better ground plane detection
            vertical_fov_angle: 0.6
            vertical_fov_padding: 0.05
            horizontal_fov_angle: 6.29
            decay_acceleration: 5.0
            model_type: 1
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0   # Slightly reduced for smoother navigation
        inflation_radius: 0.25     # Increased for better clearance
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "turtlebot3_world.yaml"

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["backup", "wait"] #"spin"
    #spin:
      #plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: False
    simulate_ahead_time: 5.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"   
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200
