slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS TF and scan setup
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping

    debug_logging: true
    throttle_scans: 1
    transform_publish_period: 0.02
    map_update_interval: 0.5
    resolution: 0.05
    minimum_laser_range: 0.5
    maximum_laser_range: 25.0
    minimum_time_interval: 0.25
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # General scan matcher parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.0
    minimum_travel_heading: 0.0
    scan_buffer_size: 80
    scan_buffer_maximum_scan_distance: 25.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5

    # Loop closure settings (optimized)
    do_loop_closing: true
    loop_search_maximum_distance: 5.0
    loop_match_minimum_chain_size: 3
    loop_match_maximum_variance_coarse: 5.0
    loop_match_minimum_response_coarse: 0.25
    loop_match_minimum_response_fine: 0.30

    # Correlation - standard matching
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Correlation - loop closure matcher
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan matcher fine-tuning
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true

